[build]
  command = "npm run build && pip install -r backend/requirements.txt"
  functions = "backend"
  publish = "frontend/build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
